trigger:
- main


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/dbarda/check_project_to_eliad.git
    cd check_project_to_eliad
    git checkout main
    # Additional commands to prepare the repository (if needed)
  displayName: 'Clone GitHub Repo'
  workingDirectory: $(Agent.TempDirectory)

- script: |
    # Create a ZIP archive of the cloned contents
    zip -r --password ${PASS} dudu.zip .
  displayName: 'Create ZIP Archive'
  workingDirectory: $(Agent.TempDirectory)/check_project_to_eliad

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/check_project_to_eliad/dudu.zip'
    artifact: 'myartifact'
  displayName: 'Publish Artifact'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git clone https://github.com/dbarda/test.git
      cd test
      git status
      git add .
      git commit -m  "dfgfr"
      git push origin main
      git config --global user.email "you@example.com"
      git config --global user.name "g_dbarda"
    workingDirectory: $(Agent.TempDirectory)/check_project_to_eliad
  displayName: 'Clone Destination Repo and Upload ZIP Archive'
  
  

- script: |
    # Optionally clean up temporary files
    rm -rf $(Agent.TempDirectory)
  displayName: 'Clean Up'
