trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/dbarda/check_project_to_eliad.git
    cd check_project_to_eliad
    git checkout main
    # Additional commands to prepare the repository (if needed)
  displayName: 'Clone GitHub Repo'
  workingDirectory: $(Agent.TempDirectory)

- script: |
    # Create a ZIP archive of the cloned contents
    zip -r dudu.zip .
  displayName: 'Create ZIP Archive'
  workingDirectory: $(Agent.TempDirectory)/check_project_to_eliad

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/check_project_to_eliad/dudu.zip'
    artifact: 'myartifact'
  displayName: 'Publish Artifact'

- script:
    git clone https://github.com/dbarda/test.git
    cd test
    git status
    git add .
    git commit -m "Your commit message here"
    git push origin main
  displayName: 'Clone Destination Repo and Upload ZIP Archive'
  workingDirectory: $(Agent.TempDirectory)

- script: |
    # Optionally clean up temporary files
    rm -rf $(Agent.TempDirectory)
  displayName: 'Clean Up'
