trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://github.com/dbarda/check_project_to_eliad.git
    git checkout main
    # Additional commands to prepare the repository (if needed)
  displayName: 'Clone GitHub Repo'
  workingDirectory: $(Agent.TempDirectory)

- script: |
    # Create a ZIP archive of the cloned contents
    zip -r myarchive.zip .
  displayName: 'Create ZIP Archive'
  workingDirectory: $(Agent.TempDirectory)/source-repo

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Agent.TempDirectory)/source-repo/myarchive.zip'
    artifact: 'myartifact'
  displayName: 'Publish Artifact'

- script: |
    git clone https://github.com/dbarda/check_project_to_eliad.git
    cd destination-repo
    # Additional commands to configure and prepare the destination repo (if needed)
    git add .
    git commit -m "Add ZIP archive"
    git push origin main
  displayName: 'Clone Destination Repo and Upload ZIP Archive'
  workingDirectory: $(Agent.TempDirectory)

- script: |
    # Optionally clean up temporary files
    rm -rf $(Agent.TempDirectory)
  displayName: 'Clean Up'
